### PR TITLE
Add .gitattributes

### PR DESCRIPTION
**Pull request by fezfez**
This will drop downloaded package size drastically

before : 114 items, size 201,6 kB
after : 57 items, size 97,7 kB

### CODE REVIEW

**Comment by fezfez** [comment]
Ping! 🙃

**Comment by fezfez** [comment]
ping ?

**Review by Nyholm — APPROVED** [review]

**Comment by fezfez** [comment]
since there is no activity i have created a fork

https://packagist.org/packages/fezfez/backup-manager
for league v1 => https://packagist.org/packages/fezfez/backup-manager-league-flysystem-v1
for league v2 => https://packagist.org/packages/fezfez/backup-manager-league-flysystem-v3

**Comment by Nyholm** [comment]
Hey @fezfez, should we try to contact @ShawnMcCool on Twitter or email to ask to help with maintenance?

**Comment by fezfez** [comment]
almost 2 year with ping... 6 hours to to get the package as clean as i want + with lastest deps, i want to move on...

**Pull request closed without merging**
