### PR TITLE
First argument of Process::__construct must be an array (now throwing…

### PR DESCRIPTION
**Pull request by Ali1**
… error as typehinted)

### CODE REVIEW

**Comment by ShawnMcCool** [comment]
I'm concerned that this will break backwards compatibility. Do you have thoughts?

**Comment by Ali1** [comment]
It wouldn't. It was always supposed to be an array but previously it would not throw errors.

**Comment by ShawnMcCool** [comment]
I looked at the documentation here https://symfony.com/doc/2.1/components/process.html

Within I found this code example from 2.1 of the process component in which the constructor is taking a string.

image

The currently supported versions of process found in https://github.com/backup-manager/backup-manager/blob/master/composer.json are:

"symfony/process": "^2.1 || ^3.0 || ^4 || ^5",

While I can easily make the argument that since 2.x is no longer supported then we shouldn't support it either. However it seems to affect backwards compatibility.

I think we just need to tag a new major version even though the backwards compatibility impact is minor. The 3.x version is still maintained so we should probably not drop that.

Do you have thoughts on this?

**Comment by Ali1** [comment]
great

**Comment by ShawnMcCool** [comment]
I tagged with 3.0

**Pull request merged**
