### PR TITLE
Added endpoint to awsS3 to support digital ocean spaces

### PR DESCRIPTION
**Pull request by MeRoBo**
Give support for Digital Ocean Spaces via the s3 driver by enforcing the endpoint instead of auto-discovering back to the amazon domain.

### CODE REVIEW

**Comment by MeRoBo** [comment]
Relates to - https://github.com/backup-manager/laravel/issues/102

**Comment by herryswastika** [comment]
image
thanks

**Comment by MeRoBo** [comment]
@ShawnMcCool - Is there anything else I need to do here to get this merged?

**Comment by ShawnMcCool** [comment]
Yeah, it's usually just to ping me. =)

**Pull request merged**
