### PR TITLE
Fixed branch alias

### PR DESCRIPTION
**Pull request by GrahamCampbell**
@ShawnMcCool This is REALLY important.

### CODE REVIEW

**Comment by ShawnMcCool** [comment]
What precisely should it be set to?

**Comment by GrahamCampbell** [comment]
`1.0-dev` or `1.0.x-dev`, but not `1.0`. `1.0` would be telling composer, the master branch litterally is `1.0.0`.

**Comment by ShawnMcCool** [comment]
Ok, I understand how it works. Thanks.

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
