### PR TITLE
Allow symfony/process ^6.0

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by trsteel88** [comment]
Is this project still maintained?

**Review by Nyholm — APPROVED** [review]
I agree with this. 
Thank you

**Comment by trsteel88** [comment]
@Nyholm, is there a typo in https://github.com/backup-manager/symfony/blob/master/composer.json#L19

It says it requires "backup-manager/backup-manager" ^3.0. However, this package is currently tagged at 1.1.1 (not 3.0)?

**Comment by fezfez** [comment]
@trsteel88 : no, you can see the list of tags here : https://github.com/backup-manager/backup-manager/tags, it contains 3.0.0.
I think they didnt use release github feature to tag

**Comment by trsteel88** [comment]
Oh of course. Thanks @fezfez.

> I agree with this. Thank you

Are you fine to merge this in @Nyholm?

**Comment by fezfez** [comment]
@Nyholm ping 🙂

**Comment by Nyholm** [comment]
I dont have write permissions to this repository. Only the Symfony bundle. 

(hence my review check is not green)
Screenshot 2022-02-21 at 09 06 40

@ShawnMcCool can you help here?

**Comment by fezfez** [comment]
since there is no activity i have created a fork

https://packagist.org/packages/fezfez/backup-manager
for league v1 => https://packagist.org/packages/fezfez/backup-manager-league-flysystem-v1
for league v2 => https://packagist.org/packages/fezfez/backup-manager-league-flysystem-v3

**Pull request closed without merging**
