### PR TITLE
Add mongodb export

### PR DESCRIPTION
**Pull request by hansvn**
This pull request adds exports for mongodb.

### CODE REVIEW

**Comment by sgasser** [comment]
@hansvn are you using this and works?

@mitchellvanw do you will merge or decline this PR?

**Comment by hansvn** [comment]
@sgasser yes, I am using this in a production environment and is working.

**Comment by sgasser** [comment]
@mitchellvanw @ShawnMcCool Why do you not merge this PR?
Could you tell us what's wrong with this PR?

**Comment by hansvn** [comment]
I created a new version to be able to work correctly in laravel environments.

**Comment by sgasser** [comment]
This is my solution: https://github.com/sgasser/backup-manager/commit/341995ae13f5bfeab0d1bc1c6fcfe0e9ed7016c6

Including restore and "create archive" command with mongodump (--archive)

**Comment by ShawnMcCool** [comment]
Hello, sorry for being slow. Do you feel like this PR is ready to merge?

**Comment by ShawnMcCool** [comment]
Sorry, time out. Would revisit.

**Pull request closed without merging**
